- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Enums/ActionResponseType.cs
- ChustaSoft.Common/Enums/ErrorType.cs
- ChustaSoft.Common/Exceptions/BusinessException.cs
- ChustaSoft.Common/Exceptions/ElementNotFoundException.cs
- ChustaSoft.Common/Exceptions/EnumNotFoundException.cs
- ChustaSoft.Common/Helpers/ActionResponseBuilder.cs
- ChustaSoft.Common/Helpers/CollectionsHelper.cs
- ChustaSoft.Common/Helpers/EnumsHelper.cs
- ChustaSoft.Common/Helpers/UriHelper.cs
- ChustaSoft.Common/Utilities/ActionResponse.cs
- ChustaSoft.Common/Utilities/ErrorMessage.cs
- ChustaSoft.Common/Utilities/PaginatedList.cs
- ChustaSoft.Common/Utilities/SerializableCollection.cs
- ChustaSoft.Common/Utilities/ThreadSafeList.cs
Version 1.0.4 for Nuget
- ActionResponseBuilder with TDD
- NuGet and general documentation
- Added more Test Cases
> Version 1.0.4

- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/ActionResponseBuilder.cs
Added AddData method by TDD at ActionResponseBuilder
> Version 1.0.5

- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Exceptions/BusinessException.cs
Solution fix for RESX DependentUpon
Added new constructor with single string parameter for BusinessException
> Version 1.06

- ChustaSoft.Common.UnitTest/TestServices/UriHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/UriHelper.cs
Fixed bug with UriBuilder AddPathPart
> Version 1.0.8

- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderHelperUnitTest.cs
- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/ActionResponseBuilder.cs
- ChustaSoft.Common/Helpers/ActionResponseBuilderHelper.cs
- ChustaSoft.Common/Resources/ExceptionResources.Designer.cs
- ChustaSoft.Common/Resources/ExceptionResources.es-ES.resx
- ChustaSoft.Common/Resources/ExceptionResources.resx
Added new functionality for allowing add elements in ActionResponseBuilder
> Version 1.0.10

- ChustaSoft.Common.UnitTest/TestServices/EnumsHelperUnitTest.cs
- ChustaSoft.Common.UnitTest/TestServices/StringHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/EnumsHelper.cs
- ChustaSoft.Common/Helpers/StringHelper.cs
- ChustaSoft.Common/Resources/ExceptionResources.Designer.cs
- ChustaSoft.Common/Resources/ExceptionResources.es-ES.resx
- ChustaSoft.Common/Resources/ExceptionResources.resx
Added StringExtensions to CommonNET
- FirstToUpper
- FirstToLower
- ToUpperCamelCase
> Versión 1.0.11

- README.md
Added new methods for EnumsHelper:
- GetByString
- GetEnumList
- GetEnumDictionary
- Added missing documentation for String Exentesion methods from version 1.0.11
> Version 1.0.12

- ChustaSoft.Common.UnitTest/TestServices/ISelectablePropertiesBuilderHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/SelectablePropertiesBuilderHelper.cs
- ChustaSoft.Common/Models/PropertyInfo.cs
- ChustaSoft.Common/Utilities/ISelectablePropertiesBuilder.cs
- ChustaSoft.Common/Utilities/SelectablePropertiesBuilder.cs
Added new functionality for SelectableProperties:
- Model
- Builder
- Extension methods
- UnitTesting
> Version 1.0.13

- ChustaSoft.Common.UnitTest/TestServices/SelectablePropertiesBuilderHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/SelectablePropertiesBuilderHelper.cs
- ChustaSoft.Common/Models/SelectablePropertiesContext.cs
- ChustaSoft.Common/Utilities/SelectablePropertiesBuilder.cs
- Added SelectablePropertiesBuilder for nested collections
> Version 1.0.15-beta

- ChustaSoft.Common/ChustaSoft.Common.csproj
> Version 1.0.15

- ChustaSoft.Common.UnitTest/TestServices/SelectablePropertiesBuilderHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/IMapper.cs
- ChustaSoft.Common/Helpers/SelectablePropertiesBuilderHelper.cs
- ChustaSoft.Common/Utilities/SelectablePropertiesBuilder.cs
Added IMapper interface
Added GetSelection method for SelectablePropertiesBuilder
Added ThenSelectFromProperty method to SelectablePropertiesBuilderHelper
> Version 1.0.16

- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Resources/ExceptionResources.fr-FR.resx
Updated references on UnitTest project for collecting Code Coverage
> Updated references on UnitTest project

- ChustaSoft.Common.UnitTest/TestServices/EncryptationHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/EncryptationHelper.cs
> Version 1.0.18.0

- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/ActionResponseBuilder.cs
Added SetStatus by boolean to ActionResponseBuilder
> Version 1.0.20

- ChustaSoft.Common.UnitTest/TestServices/SelectablePropertiesBuilderHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/SelectablePropertiesBuilderHelper.cs
- ChustaSoft.Common/Models/SelectablePropertiesContext.cs
- ChustaSoft.Common/Utilities/SelectablePropertiesBuilder.cs
Bugs solved:
- #21: Concurrency error on CommonNET SelectablePropertyBuilder
> Version 1.0.20.1

- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Enums/ErrorType.cs
- ChustaSoft.Common/Helpers/IBuilder.cs
- ChustaSoft.Common/Utilities/ErrorMessage.cs
New implementations:
- IBuilder added
> Version 1.0.21

- ChustaSoft.Common.UnitTest/TestServices/EncryptationHelperUnitTest.cs
- ChustaSoft.Common/Helpers/EncryptationHelper.cs
Add Encrypt/Decrypt functionality #24
> Version 1.0.22

- ChustaSoft.Common.AspNet/Base/ApiControllerBase.cs
- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/ActionResponseBuilder.cs
- ChustaSoft.Common/Helpers/IBuilder.cs
- ChustaSoft.CommonNET.sln
ChustaSoft.Common.AspNet [1.0.1] 
- Created library
- Base Controller created
ChustaSoft.Common [1.0.22.1]
- static method for create ActionResponseBuilder
> ChustaSoft.Common.AspNet [1.0.1] and ChustaSoft.Common [1.0.22.1]

- ChustaSoft.Common.AspNet/Base/ApiControllerBase.cs
- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderHelperUnitTest.cs
- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderUnitTest.cs
- ChustaSoft.Common.UnitTest/TestServices/SelectablePropertiesBuilderHelperUnitTest.cs
- ChustaSoft.Common/Builders/ActionResponseBuilder.cs
- ChustaSoft.Common/Builders/SelectablePropertiesBuilder.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Contracts/IBuilder.cs
- ChustaSoft.Common/Contracts/IMapper.cs
- ChustaSoft.Common/Helpers/ActionResponseBuilderHelper.cs
- ChustaSoft.Common/Helpers/SelectablePropertiesBuilderHelper.cs
Changed some namespaces:
- Added Builders namespace
- Added Contracts namespace
> CommonNET [1.1.0]

- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common.UnitTest/TestHelpers/GeneralTestHelper.cs
- ChustaSoft.Common.UnitTest/TestServices/EncryptationHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/EncryptationHelper.cs
Allowed to encrypt and decrypt JSON objects
> Version 1.1.1

- ChustaSoft.Common.UnitTest/TestServices/ReflectionHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/ReflectionHelper.cs
- ChustaSoft.Common/Models/PropertyInfo.cs
> Version 1.1.2

- ChustaSoft.Common.UnitTest/TestHelpers/GeneralTestHelper.cs
- ChustaSoft.Common.UnitTest/TestServices/ReflectionHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/ReflectionHelper.cs
Allowed to clear objects by reflection even if they have Indexer
> Version 1.1.3

- ChustaSoft.Common.UnitTest/TestHelpers/GeneralTestHelper.cs
- ChustaSoft.Common.UnitTest/TestServices/EnumsHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/EncryptationHelper.cs
- ChustaSoft.Common/Helpers/EnumsHelper.cs
Added documentation to EncryptionHelper
Added GetAttirubtes to EnumsHelper
> Version 1.1.4

- ChustaSoft.Common.UnitTest/TestServices/EncryptationHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Exceptions/UnsupportedAlgorithmException.cs
- ChustaSoft.Common/Helpers/EncryptationHelper.cs
- ChustaSoft.Common/Resources/ExceptionResources.Designer.cs
- ChustaSoft.Common/Resources/ExceptionResources.es-ES.resx
- ChustaSoft.Common/Resources/ExceptionResources.fr-FR.resx
- ChustaSoft.Common/Resources/ExceptionResources.resx
Implemented multiple key configurations for Encrypt and Decrypt operations
> Version 1.1.5

- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common/ChustaSoft.Common.csproj
Added .NET Core 3.0 and above compatibility
> Version 1.3.0

- ChustaSoft.Common.UnitTest/TestServices/CollectionsHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/CollectionsHelper.cs
Implemented AddRange Extension method for ConcurrentBag
> Version 1.2.1

- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.WPF/Models/SelectableOption.cs
> [WPF]: Version 1.0.1 -> SelectableOption generic

- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.WPF/Models/SelectableOption.cs
Bugs solved:
#44 : Functional fix solved, Value was applied to property Name (invalid)
> [WPF]: Version 1.0.2 -> SelectableOption generic functional fix

- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.WPF/Helpers/SelectableOptionExtensions.cs
#44: SelectableOption Extension methods
> [WPF]: Version 1.0.3 -> SelectableOption Extension methods

- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.WPF/Controls/Loading.xaml
- ChustaSoft.Common.WPF/Controls/Loading.xaml.cs
Version 1.1.0
#43 : Create Login control
> [WPF]: Version 1.1.0 -> Loading control

- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.WPF/Controls/Loading.xaml
Version 1.1.1
Bugs solved:
#43 : Fix element name
> [WPF]: Version 1.1.1 -> Loading control fix

- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Contracts/IAuditable.cs
- ChustaSoft.Common/Contracts/IKeyable.cs
Version XX.XX.XX
- New IKeyable interface
- New IAuditable interface
> [CommonNET]: Version 1.3.0

- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Contracts/IAuditable.cs
Added public visibility to IAuditable
> [CommonNET]: Version 1.3.1

- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Contracts/IAuditable.cs
IAuditable nullable LastModificationDate
> [CommonNET]: Version 1.3.2

- ChustaSoft.Common.AspNet.UnitTest/ChustaSoft.Common.AspNet.UnitTest.csproj
- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.Wpf.UnitTest/ChustaSoft.Common.Wpf.UnitTest.csproj
- ChustaSoft.Common/ChustaSoft.Common.csproj
Version 2.0.1
- Project references update
- Explicit support for .NET Core 3.1 .NET Framework 4.7.1 and NET 5.0
> Project references update and explicit support for .NET Core and .NET Framework

- ChustaSoft.Common.AspNet.UnitTest/BaseTests/ApiControllerBaseTest.cs
- ChustaSoft.Common.AspNet/Base/ApiControllerBase.cs
- ChustaSoft.Common.AspNet/Base/MvcControllerBase.cs
- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.UnitTest/TestHelpers/GeneralTestHelper.cs
- ChustaSoft.Common.UnitTest/TestServices/ActionResponseBuilderUnitTest.cs
- ChustaSoft.Common.UnitTest/TestServices/CollectionsHelperUnitTest.cs
- ChustaSoft.Common.UnitTest/TestServices/EnumsHelperUnitTest.cs
- ChustaSoft.Common.UnitTest/TestServices/StringHelperUnitTest.cs
- ChustaSoft.Common.WPF/Base/ViewModelBase.cs
- ChustaSoft.Common.WPF/Controls/Loading.xaml.cs
- ChustaSoft.Common.WPF/Controls/MultiSelection.xaml.cs
- ChustaSoft.Common.WPF/Controls/Selection.xaml.cs
- ChustaSoft.Common.WPF/Helpers/RelayCommand.cs
- ChustaSoft.Common.WPF/Helpers/SelectableOptionExtensions.cs
- ChustaSoft.Common.WPF/Models/SelectableOption.cs
- ChustaSoft.Common.Wpf.UnitTest/BaseTests/ViewModelBaseTest.cs
- ChustaSoft.Common.Wpf.UnitTest/HelperTests/SelectableOptionExtensionsUnitTest.cs
- ChustaSoft.Common/Contracts/IBuilder.cs
- ChustaSoft.Common/Exceptions/EnumNotFoundException.cs
- ChustaSoft.Common/Helpers/EncryptationHelper.cs
- ChustaSoft.Common/Helpers/EnumsHelper.cs
- ChustaSoft.Common/Helpers/ReflectionHelper.cs
- ChustaSoft.Common/Helpers/StringHelper.cs
- ChustaSoft.Common/Helpers/UriHelper.cs
- ChustaSoft.Common/Utilities/ErrorMessage.cs
Adding MvcController to AspNet package
> AspNet package version [2.0.3]

- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.AspNet/Configuration/IApplicationBuilderExtensions.cs
- ChustaSoft.Common.AspNet/Middlewares/HttpContextLoggingMiddleware.cs
- Added:
- HttpContextLoggingMiddleware
> [AspNet]: Version 2.0.4

- ChustaSoft.Common.AspNet.UnitTest/ChustaSoft.Common.AspNet.UnitTest.csproj
- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.Wpf.UnitTest/ChustaSoft.Common.Wpf.UnitTest.csproj
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.CommonNET.sln
- README.md
- CommonNET:
- .NET 6.0 support added
- .NET 4.8 support added
- CommonNET ASPNET:
- .NET 6.0 support added
- CommonNET WPF:
- .NET 6.0 (windows) support added
> .NET 6.0 upgrade in all libraries

- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.UnitTest/TestServices/StreamHelperUnitTest.cs
- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/StreamHelper.cs
Added: 
- Stream compression / decompression 
- Steam comparison
- String bridge to stream compression
> CommonNET version [2.0.5] : Added Stream utilities helper class

- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common.UnitTest/Resources/test-json-file.json
- ChustaSoft.Common.UnitTest/TestServices/ReflectionHelperUnitTest.cs
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Helpers/ReflectionHelper.cs
- ChustaSoft.Common/Helpers/StreamHelper.cs
- StreamHelper:
-   GetEmbeddedResource
- AsString
> [CommonNET] Version [2.6.0]

- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/Exceptions/ModelMappingException.cs
- ChustaSoft.Common/Resources/ExceptionResources.Designer.cs
- ChustaSoft.Common/Resources/ExceptionResources.es-ES.resx
- ChustaSoft.Common/Resources/ExceptionResources.fr-FR.resx
- ChustaSoft.Common/Resources/ExceptionResources.resx
- Implemented ModelMappingException
> CommonNET [2.7.0] : Implemented ModelMappingException

- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.AspNet/Configuration/IApplicationBuilderExtensions.cs
- ChustaSoft.Common.AspNet/Middlewares/ErrorHandlerMiddleware.cs
Version 2.4.0
Created by: Jose Luis Eiguren
ChustaSoft.Common.AspNet => add error handler middleware to trap any unhandled exception
> Add error hanlder middleware

- ChustaSoft.Common.AspNet.UnitTest/ApiControllerBaseTest.cs
- ChustaSoft.Common.AspNet.UnitTest/ChustaSoft.Common.AspNet.UnitTest.csproj
- ChustaSoft.Common.AspNet/Base/ApiControllerBase.cs
- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.AspNet/Configuration/IApplicationBuilderExtensions.cs
- ChustaSoft.Common.AspNet/Extensions/ControllerBaseExtensions.cs
- ChustaSoft.Common.AspNet/Middlewares/ErrorHandlerMiddleware.cs
- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common.Wpf.UnitTest/ChustaSoft.Common.Wpf.UnitTest.csproj
Version 2.4.0
Created by: Jose Luis Eiguren
- ChustaSoft.Common.AspNet => add error handler middleware to trap any unhandled error
- ChustaSoft.Common.AspNet => ApiControllerBase: add get user id from request access token
> AspNet [2.4.0] : Added GetUserId and ErrorHandlerMiddleware

- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.AspNet/Extensions/ControllerBaseExtensions.cs
- ChustaSoft.Common.AspNet/changelog.md
- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.WPF/changelog.md
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/changelog.md
- Changelog implemented in all packages
- namespace enhancement for AspNet Core package
> [CommonNET: 2.7.1] [AspNet:2.6.0] [WPF: 2.5.0] 

- ChustaSoft.Common.AspNet/Base/ApiControllerBase.cs
- ChustaSoft.Common.AspNet/Base/MvcControllerBase.cs
- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.AspNet/changelog.md
Fixing critical bug in Base Controller invoking extension methods with similar name
> AspNet package [2.7.1]

- ChustaSoft.Common.AspNet.UnitTest/ChustaSoft.Common.AspNet.UnitTest.csproj
- ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
- ChustaSoft.Common.AspNet/changelog.md
- ChustaSoft.Common.UnitTest/ChustaSoft.Common.UnitTest.csproj
- ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
- ChustaSoft.Common.WPF/changelog.md
- ChustaSoft.Common.Wpf.UnitTest/ChustaSoft.Common.Wpf.UnitTest.csproj
- ChustaSoft.Common/ChustaSoft.Common.csproj
- ChustaSoft.Common/changelog.md
- README.md
- Added .NET 7 compatibility
- Removed EOL .NET skd's
- Test projects dependencies upgraded
> .NET Maintenability
